import './globals.css'

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </head>
            <body>
                <div className="flex justify-center">
                    <div className="container mt-10">{children}</div>
                </div>
            </body>
        </html>
    )
}
